<link href='/assets/css/fullcalendar.min.css' rel='stylesheet' />
<link href='/assets/css/fullcalendar.print.min.css' rel='stylesheet' media='print' />

<style>

	body {
		margin: 40px 10px;
		padding: 0;
		font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
		font-size: 14px;
	}

	#calendar {
		max-width: 900px;
		margin: 0 auto;
	}

	#calendar button {
    	line-height: unset;
	}

</style>